'use strict';
// Builds one corpus of the owner's own words, drawn from every assistant they use.
//
// The owner asked for the conversation logs to be brought together so BigKiji can grow
// from them. The logs are NOT moved: ~/.claude/projects is what `claude --resume` reads,
// ~/.codex and ~/.pi are the same for their tools, and relocating them would delete
// those tools' history. Originals stay put; this reads them and writes a normalised,
// redacted extract into the app's own data root.
//
// What is extracted is only the owner's turns. Of the ~2.2 GB of raw transcripts the
// vast majority is assistant output and tool results; the owner's own instructions,
// corrections and decisions are the part that carries signal, and they are tiny.
//
// Ingestion is incremental: each source file is remembered by size and mtime, so a
// re-run costs one stat per file rather than a full re-read.

const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');
const readline = require('readline');

const { redactPayload } = require('../pi-agent/../pi-core/security/payload-redactor');

// Claude Code injects a lot of machine-authored text under the `user` role: hook output,
// command results, reminders, the caveat banner. None of it is the owner speaking, and
// including it would teach BigKiji its own scaffolding.
const MACHINE_MARKERS = [
  '<system-reminder>', '<local-command-stdout>', '<command-name>', '<command-message>',
  '<command-args>', 'Caveat: The messages below were generated by the user while running',
  '[Request interrupted', 'This is an automated background-task event',
  '<task-notification>', 'tool_use_id', '[決定論ルーティング]',
];

const MIN_CHARS = 4;
const MAX_CHARS = 8000;

function isOwnerText(text) {
  const value = String(text || '').trim();
  if (value.length < MIN_CHARS) return false;
  return !MACHINE_MARKERS.some((marker) => value.includes(marker));
}

// Claude's message content is either a string or a list of blocks; only text blocks
// are the owner talking. Images and tool results are not.
function flattenContent(content) {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return '';
  return content.filter((part) => part && part.type === 'text').map((part) => part.text || '').join('\n');
}

// One adapter per transcript format. Each returns the owner's text for a parsed line,
// or '' when the line is anything else.
const ADAPTERS = {
  claude: (row) => (row.type === 'user' && row.message?.role === 'user' ? flattenContent(row.message.content) : ''),
  codex: (row) => (typeof row.text === 'string' ? row.text : ''),
  pi: (row) => (row.type === 'message' && row.message?.role === 'user' ? flattenContent(row.message.content) : ''),
  bigkiji: (row) => (row.type === 'owner' || (row.type === 'conversation' && row.role === 'owner') ? row.text || '' : ''),
};

function sourceRoots(home = os.homedir(), dataRoot = '') {
  return [
    { id: 'claude', dir: path.join(home, '.claude', 'projects'), pattern: /\.jsonl$/, adapter: 'claude' },
    { id: 'codex', dir: path.join(home, '.codex'), pattern: /^history\.jsonl$/, adapter: 'codex' },
    { id: 'pi', dir: path.join(home, '.pi', 'agent', 'sessions'), pattern: /\.jsonl$/, adapter: 'pi' },
    { id: 'bigkiji', dir: path.join(dataRoot || path.join(home, 'BigKijiUniverse'), 'sessions'), pattern: /\.jsonl$/, adapter: 'bigkiji' },
  ];
}

function listFiles(dir, pattern, depth = 4) {
  const found = [];
  const stack = [[dir, 0]];
  while (stack.length) {
    const [current, level] = stack.pop();
    if (level > depth) continue;
    let entries = [];
    try { entries = fs.readdirSync(current, { withFileTypes: true }); } catch (_) { continue; }
    for (const entry of entries) {
      const full = path.join(current, entry.name);
      if (entry.isDirectory()) { stack.push([full, level + 1]); continue; }
      if (pattern.test(entry.name)) found.push(full);
    }
  }
  return found.sort();
}

function fingerprint(text) {
  return crypto.createHash('sha256').update(text).digest('hex').slice(0, 16);
}

class CorpusIngest {
  constructor({ corpusRoot, home = os.homedir(), dataRoot = '' } = {}) {
    if (!corpusRoot) throw new Error('CorpusIngest requires corpusRoot');
    this.corpusRoot = corpusRoot;
    this.home = home;
    this.dataRoot = dataRoot;
    this.turnsFile = path.join(corpusRoot, 'owner-turns.jsonl');
    this.stateFile = path.join(corpusRoot, 'ingest-state.json');
  }

  loadState() {
    try { return JSON.parse(fs.readFileSync(this.stateFile, 'utf8')); }
    catch (_) { return { version: 1, files: {}, seen: [] }; }
  }

  saveState(state) {
    fs.mkdirSync(this.corpusRoot, { recursive: true });
    fs.writeFileSync(this.stateFile, JSON.stringify(state, null, 2));
  }

  async ingestFile(file, adapter, sourceId, seen, sink) {
    let added = 0;
    const stream = fs.createReadStream(file, { encoding: 'utf8' });
    const lines = readline.createInterface({ input: stream, crlfDelay: Infinity });
    for await (const line of lines) {
      if (!line.trim()) continue;
      let row = null;
      try { row = JSON.parse(line); } catch (_) { continue; }
      const raw = ADAPTERS[adapter](row);
      if (!isOwnerText(raw)) continue;
      const text = String(raw).trim().slice(0, MAX_CHARS);
      const id = fingerprint(text);
      // The same instruction often appears in several transcripts (a resumed session, a
      // retried run). Keep one copy so repetition does not become emphasis.
      if (seen.has(id)) continue;
      seen.add(id);
      // Redact before anything is written. The corpus is meant to be readable and
      // reusable, so a leaked key here would outlive the transcript it came from.
      const clean = redactPayload(text);
      if (clean.blocked) continue;
      sink.write(`${JSON.stringify({
        id,
        source: sourceId,
        file: file.replace(this.home, '~'),
        ts: row.timestamp || row.ts || (row.ts === 0 ? 0 : null) || null,
        cwd: row.cwd || null,
        text: clean.text,
        chars: clean.text.length,
      })}\n`);
      added += 1;
    }
    return added;
  }

  async run({ onProgress = () => {} } = {}) {
    fs.mkdirSync(this.corpusRoot, { recursive: true });
    const state = this.loadState();
    const seen = new Set(state.seen || []);
    const sink = fs.createWriteStream(this.turnsFile, { flags: 'a' });
    const summary = { scanned: 0, skipped: 0, added: 0, bySource: {} };

    for (const source of sourceRoots(this.home, this.dataRoot)) {
      for (const file of listFiles(source.dir, source.pattern)) {
        let stat = null;
        try { stat = fs.statSync(file); } catch (_) { continue; }
        summary.scanned += 1;
        const key = file.replace(this.home, '~');
        const previous = state.files[key];
        // Unchanged since last time: one stat, no read.
        if (previous && previous.size === stat.size && previous.mtimeMs === stat.mtimeMs) { summary.skipped += 1; continue; }
        const added = await this.ingestFile(file, source.adapter, source.id, seen, sink);
        state.files[key] = { size: stat.size, mtimeMs: stat.mtimeMs, added, at: new Date().toISOString() };
        summary.added += added;
        summary.bySource[source.id] = (summary.bySource[source.id] || 0) + added;
        onProgress({ file: key, added });
      }
    }

    await new Promise((resolve) => sink.end(resolve));
    state.seen = [...seen];
    state.updatedAt = new Date().toISOString();
    this.saveState(state);
    summary.total = seen.size;
    summary.turnsFile = this.turnsFile;
    return summary;
  }
}

module.exports = { CorpusIngest, ADAPTERS, isOwnerText, flattenContent, sourceRoots, MACHINE_MARKERS };
