'use strict';
const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('bigkiji', {
  onBusEvent: (cb) => ipcRenderer.on('bus:event', (_e, evt) => cb(evt)),
  onPtyData: (cb) => ipcRenderer.on('pty:data', (_e, data) => cb(data)),
  ptyInput: (data) => ipcRenderer.send('pty:input', data),
  ptyResize: (cols, rows) => ipcRenderer.send('pty:resize', { cols, rows }),
  openMain: () => ipcRenderer.send('open-main'),
  openConsole: () => ipcRenderer.send('open-console'),
  onOpenSettings: (cb) => ipcRenderer.on('ui:open-settings', () => cb()),
  trayRender: (payload) => ipcRenderer.send('tray:render', payload),
  onDeliverables: (cb) => ipcRenderer.on('vault:deliverables', (_e, items) => cb(items)),
  onVaultFiles: (cb) => ipcRenderer.on('vault:files', (_e, files) => cb(files)),
  onVaultTouch: (cb) => ipcRenderer.on('vault:touch', (_e, paths) => cb(paths)),
  reveal: (p) => ipcRenderer.send('reveal', p),
  fileDetail: (p) => ipcRenderer.invoke('file:detail', p),
  onComposerFocus: (cb) => ipcRenderer.on('composer:focus', () => cb()),
  micPermission: () => ipcRenderer.invoke('mic-permission'),
  saveRecording: (buf) => ipcRenderer.invoke('save-recording', buf),
  transcribe: (p) => ipcRenderer.invoke('transcribe', p),
  voiceToggle: () => ipcRenderer.invoke('voice:toggle'),
  getPathForFile: (file) => webUtils.getPathForFile(file), // D&D: Electron32+のFile.path代替
  piToggle: () => ipcRenderer.invoke('pi:toggle'),
  piPrompt: (text) => ipcRenderer.send('pi:prompt', text),
  conversationTurn: (text, options) => ipcRenderer.invoke('conversation:turn', text, options),
  piAbort: () => ipcRenderer.send('pi:abort'),
  onPiEvent: (cb) => ipcRenderer.on('pi:event', (_e, evt) => cb(evt)),
  onPiStats: (cb) => ipcRenderer.on('pi:stats', (_e, s) => cb(s)),
  getInfo: () => ipcRenderer.invoke('get-info'),
  securitySnapshot: () => ipcRenderer.invoke('get-info').then((info) => info.security),
  onSecurityStatus: (cb) => ipcRenderer.on('security:status', (_e, status) => cb(status)),
  // v12: LIVE COMMENTARY / Swarm可視化 / フルデュプレックス音声
  onCommentary: (cb) => ipcRenderer.on('bk:commentary', (_e, c) => cb(c)),
  onSwarm: (cb) => ipcRenderer.on('bk:swarm', (_e, s) => cb(s)),
  liveToggle: () => ipcRenderer.invoke('voice:live-toggle'),
  liveUtterance: (buf) => ipcRenderer.invoke('voice:live-utterance', buf),
  voiceInterrupt: () => ipcRenderer.send('voice:interrupt'),
  voiceState: (s) => ipcRenderer.send('voice:state', s),
  onLiveState: (cb) => ipcRenderer.on('voice:live-state', (_e, s) => cb(s)),
  onLiveOwn: (cb) => ipcRenderer.on('voice:live-own', (_e, s) => cb(s)),
  onTtsChunk: (cb) => ipcRenderer.on('voice:tts-chunk', (_e, c) => cb(c)),
  onVoiceStop: (cb) => ipcRenderer.on('voice:stop', (_e, c) => cb(c)),
  onVoiceEngineStatus: (cb) => ipcRenderer.on('voice:engine-status', (_e, s) => cb(s)),
  onVoiceSla: (cb) => ipcRenderer.on('voice:sla', (_e, s) => cb(s)),
  voicePlaybackState: (s) => ipcRenderer.send('voice:playback-state', s),
  ttsStatus: () => ipcRenderer.invoke('voice:status'),
  ttsPreview: (spec) => ipcRenderer.invoke('voice:preview', spec),
  settingsGet: () => ipcRenderer.invoke('settings:get'),
  settingsUpdate: (patch) => ipcRenderer.invoke('settings:update', patch),
  settingsSecret: (id, value) => ipcRenderer.invoke('settings:secret', id, value),
  settingsSecretStatus: () => ipcRenderer.invoke('settings:secret-status'),
  onSettingsChanged: (cb) => ipcRenderer.on('settings:changed', (_e, s) => cb(s)),
  setupState: () => ipcRenderer.invoke('setup:state'),
  setupPlan: (choice) => ipcRenderer.invoke('setup:plan', choice),
  setupChooseFolder: (kind) => ipcRenderer.invoke('setup:choose-folder', kind),
  setupApply: (choice) => ipcRenderer.invoke('setup:apply', choice),
  setupRollback: () => ipcRenderer.invoke('setup:rollback'),
  setupSkip: () => ipcRenderer.invoke('setup:skip'),
  setupFinish: () => ipcRenderer.invoke('setup:finish'),
  toolsDetect: () => ipcRenderer.invoke('tools:detect'),
  toolsProbe: (id) => ipcRenderer.invoke('tools:probe', id),
  toolsProbeAll: () => ipcRenderer.invoke('tools:probe-all'),
  toolsChoose: (id) => ipcRenderer.invoke('tools:choose', id),
  workspaceState: () => ipcRenderer.invoke('workspace:state'),
  workspaceRegister: (spec) => ipcRenderer.invoke('workspace:register', spec),
  workspaceRemove: (id) => ipcRenderer.invoke('workspace:remove', id),
  workspaceUpdate: (id, patch) => ipcRenderer.invoke('workspace:update', id, patch),
  workspaceChoose: () => ipcRenderer.invoke('workspace:choose'),
  onWorkspaceChanged: (cb) => ipcRenderer.on('workspace:changed', (_e, state) => cb(state)),
  onSetupProgress: (cb) => ipcRenderer.on('setup:progress', (_e, u) => cb(u)),
  cmuxSnapshot: () => ipcRenderer.invoke('cmux:snapshot'),
  cmuxRefresh: () => ipcRenderer.invoke('cmux:refresh'),
  cmuxSelect: (surface) => ipcRenderer.invoke('cmux:select', surface),
  cmuxAction: (action, payload) => ipcRenderer.invoke('cmux:action', action, payload),
  cmuxCommand: (spec) => ipcRenderer.invoke('cmux:command', spec),
  cmuxOpenNative: (surface) => ipcRenderer.invoke('cmux:open-native', surface),
  cmuxInput: (text, surface) => ipcRenderer.send('cmux:input', text, surface),
  cmuxKey: (key, surface) => ipcRenderer.send('cmux:key', key, surface),
  onCmuxSnapshot: (cb) => ipcRenderer.on('cmux:snapshot', (_e, s) => cb(s)),
  onCmuxError: (cb) => ipcRenderer.on('cmux:error', (_e, s) => cb(s)),
  onTaskEvent: (cb) => ipcRenderer.on('task:event', (_e, task) => cb(task)),
  onTaskLog: (cb) => ipcRenderer.on('task:log', (_e, log) => cb(log)),
  onTaskStep: (cb) => ipcRenderer.on('task:step', (_e, step) => cb(step)),
  onFleet: (cb) => ipcRenderer.on('pi:fleet', (_e, fleet) => cb(fleet)),
  fleetSnapshot: () => ipcRenderer.invoke('fleet:snapshot'),
  onModelStatus: (cb) => ipcRenderer.on('model:status:update', (_e, status) => cb(status)),
  modelStatusSnapshot: () => ipcRenderer.invoke('model:status:snapshot'),
  onRelationshipSnapshot: (cb) => ipcRenderer.on('relationship:snapshot', (_e, snapshot) => cb(snapshot)),
  relationshipSnapshot: () => ipcRenderer.invoke('relationship:snapshot'),
  listTasks: () => ipcRenderer.invoke('task:list'),
  planTask: (spec) => ipcRenderer.invoke('task:plan', spec),
  prepareTasks: (spec) => ipcRenderer.invoke('task:prepare', spec),
  approveTask: (task) => ipcRenderer.invoke('task:approve', task),
  retryTask: (id) => ipcRenderer.invoke('task:retry', id),
  abortTask: (id) => ipcRenderer.invoke('task:abort', id),
  listRuns: () => ipcRenderer.invoke('run:list'),
  approveRun: (run) => ipcRenderer.invoke('run:approve', run),
  abortRun: (id) => ipcRenderer.invoke('run:abort', id),
  onRunEvent: (cb) => ipcRenderer.on('run:event', (_e, event) => cb(event)),
  listSessions: () => ipcRenderer.invoke('session:list'),
  getSession: (id) => ipcRenderer.invoke('session:get', id),
  onSessionUpdate: (cb) => ipcRenderer.on('session:update', (_e, session) => cb(session)),
  listIdeas: () => ipcRenderer.invoke('idea:list'),
  getIdea: (id) => ipcRenderer.invoke('idea:get', id),
  enhanceIdea: (idea) => ipcRenderer.invoke('idea:enhance', idea),
  approveIdeaEnhancement: (spec) => ipcRenderer.invoke('idea:enhance-approve', spec),
  planIdea: (idea) => ipcRenderer.invoke('idea:plan', idea),
  promoteIdea: (idea) => ipcRenderer.invoke('idea:promote', idea),
  archiveIdea: (idea) => ipcRenderer.invoke('idea:archive', idea),
  onConversation: (cb) => ipcRenderer.on('conversation:update', (_e, turn) => cb(turn)),
  onIdeaDraft: (cb) => ipcRenderer.on('idea:update', (_e, draft) => cb(draft)),
  onKnowledgeStatus: (cb) => ipcRenderer.on('knowledge:status', (_e, status) => cb(status)),
  onPhaseUpdate: (cb) => ipcRenderer.on('phase:update', (_e, phase) => cb(phase)),
  remoteAccess: (ensure = false) => ipcRenderer.invoke('remote:access', ensure),
  openExternal: (url) => ipcRenderer.invoke('open:external', url),
  previewStatus: () => ipcRenderer.invoke('preview:status'),
  previewStart: () => ipcRenderer.invoke('preview:start'),
  previewStop: () => ipcRenderer.invoke('preview:stop'),
  onPreviewStatus: (cb) => ipcRenderer.on('preview:status', (_e, status) => cb(status)),
  onPreviewReload: (cb) => ipcRenderer.on('preview:reload', (_e, status) => cb(status)),
  onPreviewError: (cb) => ipcRenderer.on('preview:error', (_e, status) => cb(status)),
  knowledgeState: () => ipcRenderer.invoke('knowledge:state'),
  fastRouterStatus: () => ipcRenderer.invoke('fast-router:status'),
  buildTaskReport: (detail) => ipcRenderer.invoke('report:build', detail),
  comfyStatus: () => ipcRenderer.invoke('comfy:status'),
  comfyGenerate: (spec) => ipcRenderer.invoke('comfy:generate', spec),
  comfyCancel: (jobId) => ipcRenderer.invoke('comfy:cancel', jobId),
  onComfyEvent: (cb) => ipcRenderer.on('comfy:event', (_e, event) => cb(event)),
});
